language: r
r:
  - oldrel
  - release
sudo: required
r_packages:
  - devtools
  - covr
  - pkgdown
cache:
  packages: yes
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
