#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("createLocalProject() works", {

  expect_error(
    kwb.fakin:::createLocalProject()
    # argument "project" is missing, with no default
  )

})

