#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toCumulativeID() works", {

  expect_error(
    kwb.fakin:::toCumulativeID()
    # argument "subdirs" is missing, with no default
  )

})

