#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toKey() works", {

  expect_error(
    kwb.fakin:::toKey()
    # argument "i" is missing, with no default
  )

})

