#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:52.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("is_valid_path_file() works", {

  expect_error(
    kwb.fakin:::is_valid_path_file()
    # argument "metadata" is missing, with no default
  )

})

