#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("replaceSubdirs() works", {

  expect_error(
    kwb.fakin:::replaceSubdirs()
    # argument "s" is missing, with no default
  )

})

