#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("list_files() works", {

  expect_error(
    kwb.fakin:::list_files()
    # argument "file" is missing, with no default
  )

})

