#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:36.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("utf8_to_iso_8859_1() works", {

  expect_error(
    kwb.fakin:::utf8_to_iso_8859_1()
    # argument "x" is missing, with no default
  )

})

