#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("store() works", {

  expect_error(
    kwb.fakin:::store()
    # No such file: 'tmp' in
#   'C:/Users/Micha/Desktop'.
# Available files:
#   '20130221_154303.jpg'
#   'achilles'
#   'bewerbung'
#   'Brave.lnk'
#   'desktop.ini'
#   'DigiCorder ISIO C  PVConnect Windows Media Connect - Verknüpfung.lnk'
#   'Einschulung'
#   'Entfernte Anwendungen.html'
#   'F1 2013.url'
#   'IMG_5256.JPG'
#   'Neuer Ordner'
#   'Neuer Ordner (2)'
#   'RUSTLER_2.zip'
#   'Steam.lnk'
#   'Windows 10-Update-Assistent.lnk'
  )

})

