#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:28:02.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_names_recursively() works", {

  expect_error(
    kwb.fakin:::get_names_recursively()
    # argument "x" is missing, with no default
  )

})

