#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getDictOneByOne() works", {

  expect_error(
    kwb.fakin:::getDictOneByOne()
    # argument "paths" is missing, with no default
  )

})

