#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("removeCommonRoot() works", {

  expect_error(
    kwb.fakin:::removeCommonRoot()
    # argument "x" is missing, with no default
  )

})

