#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_sha1() works", {

  expect_error(
    kwb.fakin:::read_sha1()
    # argument "file" is missing, with no default
  )

})

