#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toLongPath() works", {

  expect_error(
    kwb.fakin:::toLongPath()
    # argument "shortpath" is missing, with no default
  )

})

