#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("write_batch_list_files() works", {

  expect_error(
    kwb.fakin:::write_batch_list_files()
    # argument "output_file" is missing, with no default
  )

})

