#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:57.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("plot_horizontal_bars() works", {

  expect_error(
    kwb.fakin:::plot_horizontal_bars()
    # argument "data" is missing, with no default
  )

})

