#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("printFreqs() works", {

  expect_error(
    kwb.fakin:::printFreqs()
    # argument "x" is missing, with no default
  )

})

