#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_file_duplicates() works", {

  expect_error(
    kwb.fakin:::get_file_duplicates()
    # argument "paths" is missing, with no default
  )

})

