#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:49.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_depths_from_subdir_matrix() works", {

  expect_error(
    kwb.fakin:::get_depths_from_subdir_matrix()
    # argument "subdirs" is missing, with no default
  )

})

