#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("cut_left() works", {

  expect_error(
    kwb.fakin:::cut_left()
    # argument "start_string" is missing, with no default
  )

})

