#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:49.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("plot_files_in_depth() works", {

  expect_error(
    kwb.fakin:::plot_files_in_depth()
    # plot_files_in_depth() has been removed.
  )

})

