#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("subtree_for_treejack() works", {

  expect_error(
    kwb.fakin:::subtree_for_treejack()
    # argument "root" is missing, with no default
  )

})

