#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("replaceSpecial() works", {

  expect_error(
    kwb.fakin:::replaceSpecial()
    # argument "x" is missing, with no default
  )

})

