#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getProjectPaths() works", {

  expect_error(
    kwb.fakin:::getProjectPaths()
    # argument "startDirectory" is missing, with no default
  )

})

