#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sortedImportance() works", {

  expect_error(
    kwb.fakin:::sortedImportance()
    # argument "x" is missing, with no default
  )

})

