#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("check_or_set_ending_slash() works", {

  expect_error(
    kwb.fakin:::check_or_set_ending_slash()
    # argument "x" is missing, with no default
  )

})

