#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_paths() works", {

  expect_error(
    kwb.fakin:::read_paths()
    # argument "file" is missing, with no default
  )

})

