#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("write_metadata() works", {

  expect_error(
    kwb.fakin:::write_metadata()
    # argument "file" is missing, with no default
  )

})

