#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:33.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("boxplot_main_extensions() works", {

  expect_error(
    kwb.fakin:::boxplot_main_extensions()
    # argument "data" is missing, with no default
  )

})

