#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("ascii_stats() works", {

  expect_error(
    kwb.fakin:::ascii_stats()
    # argument "x" is missing, with no default
  )

})

