#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:34.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("build_folders_from_file() works", {

  expect_error(
    kwb.fakin:::build_folders_from_file()
    # argument "file" is missing, with no default
  )

})

