#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("flatten_tree() works", {

  expect_error(
    kwb.fakin:::flatten_tree()
    # argument "x" is missing, with no default
  )

})

