#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("remove_unwanted() works", {

  expect_error(
    kwb.fakin:::remove_unwanted()
    # argument "x" is missing, with no default
  )

})

