#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("all_path_levels() works", {

  expect_error(
    kwb.fakin:::all_path_levels()
    # argument "path" is missing, with no default
  )

})

