#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toSubdirMatrix() works", {

  expect_error(
    kwb.fakin:::toSubdirMatrix()
    # argument "dirparts" is missing, with no default
  )

})

