#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("write_object() works", {

  expect_error(
    kwb.fakin:::write_object()
    # argument "name" is missing, with no default
  )

})

