#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_biggest_folders() works", {

  expect_error(
    kwb.fakin:::plot_biggest_folders()
    # argument "tree" is missing, with no default
  )

})

