#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:41.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("merge_read_and_write_matrices() works", {

  expect_error(
    kwb.fakin:::merge_read_and_write_matrices()
    # argument "matrix_read" is missing, with no default
  )

})

