#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toFrequencyData() works", {

  expect_error(
    kwb.fakin:::toFrequencyData()
    # argument "freqs" is missing, with no default
  )

})

