#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("compressWithDictionary() works", {

  expect_error(
    kwb.fakin:::compressWithDictionary()
    # argument "dict" is missing, with no default
  )

})

