#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:59.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("find_metadata() works", {

  expect_error(
    kwb.fakin:::find_metadata()
    # argument "name" is missing, with no default
  )

})

