#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:50.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("prepare_for_scatter_plot() works", {

  expect_error(
    kwb.fakin:::prepare_for_scatter_plot()
    # argument "file_data" is missing, with no default
  )

})

