#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:48.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("plot_all_treemaps() works", {

  expect_error(
    kwb.fakin:::plot_all_treemaps()
    # argument "path_infos" is missing, with no default
  )

})

