#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:54.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read_path_information() works", {

  expect_error(
    kwb.fakin:::read_path_information()
    # argument "file_info_dir" is missing, with no default
  )

})

