#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:44.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("arrange_file_in_depth_plots() works", {

  expect_error(
    kwb.fakin:::arrange_file_in_depth_plots()
    # argument "plots_scatter" is missing, with no default
  )

})

