#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:28:05.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("sort_unique() works", {

  expect_error(
    kwb.fakin:::sort_unique()
    # argument "x" is missing, with no default
  )

})

