#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("logResultIf() works", {

  expect_error(
    kwb.fakin:::logResultIf()
    # argument "dbg" is missing, with no default
  )

})

