#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_number_of_elements_per_folder() works", {

  expect_error(
    kwb.fakin:::plot_number_of_elements_per_folder()
    # argument "x" is missing, with no default
  )

})

