#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("to_tree() works", {

  expect_error(
    kwb.fakin:::to_tree()
    # argument "x" is missing, with no default
  )

})

