#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:39.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("property_is_available() works", {

  expect_error(
    kwb.fakin:::property_is_available()
    # argument "property_names" is missing, with no default
  )

})

