#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("compressPaths() works", {

  expect_error(
    kwb.fakin:::compressPaths()
    # argument "x" is missing, with no default
  )

})

