#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-14 11:27:52.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("guess_file_path_type() works", {

  expect_error(
    kwb.fakin:::guess_file_path_type()
    # argument "x" is missing, with no default
  )

})

