#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getFrequencies() works", {

  expect_error(
    kwb.fakin:::getFrequencies()
    # non-character argument
  )

})

