#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getSubdirsByFrequence() works", {

  expect_error(
    kwb.fakin:::getSubdirsByFrequence()
    # argument "freqinfo" is missing, with no default
  )

})

