#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("to_leaf_matrix() works", {

  expect_error(
    kwb.fakin:::to_leaf_matrix()
    # argument "subdirs" is missing, with no default
  )

})

