#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("startsWithParts() works", {

  expect_error(
    kwb.fakin:::startsWithParts()
    # argument "parts" is missing, with no default
  )

})

