#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("writePathsToFiles() works", {

  expect_error(
    kwb.fakin:::writePathsToFiles()
    # argument "xall" is missing, with no default
  )

})

